platform :ios, '13.0'
use_frameworks!

target 'Debuggy_Example' do
  pod 'Debuggy', path: '../'

  target 'Debuggy_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.5'
    pod 'Nimble-Snapshots' , '~> 8.0.0'
  end
end
