# references:
# - https://docs.travis-ci.com/user/reference/osx
# - https://github.com/supermarin/xcpretty#usage

osx_image: xcode11
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- bundle install
- pod install --project-directory=Example --repo-update
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Debuggy.xcworkspace -scheme Debuggy-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
