# references:
# - https://docs.travis-ci.com/user/reference/osx
# - https://docs.travis-ci.com/user/languages/objective-c/
# - https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- bundle install
- pod install --project-directory=Example --repo-update
script:
- set -o pipefail &&
  xcodebuild test
  -workspace Example/Debuggy.xcworkspace
  -scheme Debuggy-Example
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest'
  -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
